import sys
import json

name = "World"
args = sys.argv[1:] if len(sys.argv) > 1 else []

# Parse --name argument
i = 0
while i < len(args):
    if args[i] == "--name" and i + 1 < len(args):
        name = args[i + 1]
        i += 2
    else:
        i += 1

result = {
    "greeting": f"Hello, {name}!",
    "message": "This greeting was generated by a skill script."
}
print(json.dumps(result, indent=2))
